version: "3.9"

services:
    nautilus-api:
        container_name: nautilus-api
        restart: always
        build:
            context: nautilus-api
        command: ["npm", "run", "start:dev"]
        ports: 
            - "8080:8080"
        networks: 
            - nautilus
        volumes: 
            - './nautilus-api/src/:/usr/app/src'
    nautilus-db:
        container_name: nautilus-db
        image: mongo
        ports: 
            - "27017:27017"
        environment:
            # - MONGO_INITDB_ROOT_USERNAME=root
            # - MONGO_INITDB_ROOT_PASSWORD=1234
            - MONGO_INITDB_DATABASE=nautilus
        networks: 
            - nautilus
    nautilus-db-admin:
        container_name: nautilus-db-admin
        image: mongo-express
        restart: always
        ports:
            - "8081:8081"
        environment: 
            # ME_CONFIG_MONGODB_ADMINUSERNAME: root
            # ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
            ME_CONFIG_MONGODB_SERVER: nautilus-db
        networks: 
            - nautilus
        depends_on:
            -  nautilus-db

networks:
  nautilus:
    driver: bridge